JSON_AS_ASCII = False


HOSTNAME = '192.168.31.128'
PORT = '3306'
DATABASE = 'shizhan'
USERNAME = 'root'
PASSWORD = '123qweRT!'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)


SQLALCHEMY_DATABASE_URI = DB_URI
# 设置是否跟踪每一次的更改
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = '1234'

MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = '651430117@qq.com'
MAIL_PASSWORD = 'jvbjrtoidghwbdih'
MAIL_DEFAULT_SENDER = "651430117@qq.com"
